spring:
  application:
    name: github-batch-delete

github:
  username: username
  password: password
  repositorys: repo1,repo2,repo3

chrome:
  win:
    bin: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe